---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development
script:
  - bundle exec rake validate
  - bundle exec rake spec SPEC_OPTS='--format documentation'
  - bundle exec rake lint

before_install:
  - gem update bundler

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
  allow_failures:
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 5.0"

notifications:
  email: false
